app/models.py
from werkzeug.security import generate_password_hash,check_password_hash
from . import db
from flask_login import UserMixin
from . import login_manager
from datetime import datetime

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


class User(UserMixin,db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255),index = True)
    email = db.Column(db.String(255),unique = True,index = True)
    pitch_id = db.Column(db.Integer,db.ForeignKey('pitches.id'))
    pass_secure  = db.Column(db.String(255))
    password_hash = db.Column(db.String(255))

    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.pass_secure = generate_password_hash(password)


    def verify_password(self,password):
        return check_password_hash(self.pass_secure,password)


def __repr__(self):
    return f'User {self.username}'

class Category(db.Model):
    __tablename__ = 'categories'

    id = db.Column(db.Integer, primary_key = True)
    name = db.Column(db.String(255))
    description = db.Column(db.String(350))
    pitch = db.relationship('Pitch', backref='parent_category', lazy='dynamic')

    def save_category(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_categories(cls):
        categories = Category.query.all()
        return categories


    def __repr__(self):
        return f'Category {self.name}'

class Pitch(db.Model):
    __tablename__ = 'pitches'

    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String, nullable=False)
    user_id = db.Column(db.String, nullable=False)
    pitch = db.Column(db.String, nullable=False)
    category_id = db.Column(db.Integer, db.ForeignKey("categories.id"))
    date_created = db.Column(db.DateTime, default=datetime.utcnow)


    def save_pitch(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_pitches(cls, pitch_id):
        pitches= Pitch.query.filter_by(pitches_id=pitches_id).all()
        return pitches
    # @classmethod
    # def get_categories(cls):
    #     categories = Category.query.all()
    #     return categories


    def delete(self):
        db.session.delete(self)
        db.session.commit()

    def __repr__(self):
        return f"Pitch Title: {self.title}"

    

class Comment(db.Model):
    __tablename__ = 'comments'
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
    pitches_id = db.Column(db.Integer, db.ForeignKey('pitches.id'), nullable=False)
    comment = db.Column(db.Text())

    def save(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_comments(cls, pitch_id):
        comments = Comment.query.filter_by(pitches_id=pitches_id).all()
        return comments

    def delete(self):
        db.session.delete(self)
        db.session.commit()

    def __repr__(self):
        return f'Comments: {self.comment}'

class Votes(db.Model):
    '''
    class to model votes 
    '''
    __tablename__='votes'

    id = db.Column(db. Integer, primary_key=True)
    vote = db.Column(db.Integer)
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"))
    pitches_id = db.Column(db.Integer, db.ForeignKey("pitches.id"))

    def save_vote(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_votes(cls,user_id,pitches_id):
        votes = Vote.query.filter_by(user_id=user_id, pitches_id=pitches_id).all()
        return votes

app/main/forms.py
 
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField,SubmitField
from ..models import Pitch, Comment
from wtforms.validators import DataRequired

class PitchForm(FlaskForm):
    title = StringField('Pitch Category Title', validators=[DataRequired()])
    pitch = TextAreaField('YOUR PITCH',validators=[DataRequired()])
    submit = SubmitField('SUBMIT')

class CommentForm(FlaskForm):
    comment = TextAreaField('Write a comment here',validators=[DataRequired()])
    submit = SubmitField('Submit')

class CategoryForm(FlaskForm):
    name =  StringField('Category Name', validators=[DataRequired()])
    submit = SubmitField('Create')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager



bootstrap = Bootstrap()
db = SQLAlchemy()
login_manager = LoginManager()



def create_app(config_name):

    app = Flask(__name__)

    # Creating the app configurations.
    app.config.from_object(config_options[config_name])

    # Intitializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    login_manager.session_protection = 'strong'
    login_manager.login_view = 'auth.login'
    # configure upload setUp

    # Registering the blueprint

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix='/authenticate')

    # setting config

    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main',__name__)

from .import errors,views

app/main/views.py
from flask import render_template,request,redirect,url_for, abort
from . import main
from ..models import User, Pitch, Category, Comment
from flask_login import login_required, current_user
from .forms import  PitchForm, CommentForm, CategoryForm
from .. import db

#Views
@main.route('/')
def index():
  
   
    category = Category.get_categories()


    return render_template('index.html',  category = category)

@main.route('/add/category', methods=['GET','POST'])
@login_required
def new_category():

    form = CategoryForm()

    if form.validate_on_submit():
        name = form.name.data
        new_category = Category(name=name)
        new_category.save_category()

        return redirect(url_for('.index'))

    
    title = 'New category'
    return render_template('new_category.html', category_form = form,title=title)


@main.route('/categories/<int:id>')
def category(id):
    category = Category.query.get(id)
    if category is None:
        abort(404)
    

    

    return render_template('category.html', category=category)

@main.route('/categories/new-pitch/add/<int:id>', methods=['GET', 'POST'])
@login_required
def new_pitch(id):
                                              
    form = PitchForm()
    category = Category.query.filter_by(id=id).first()

    if category is None:
        abort(404)

    if form.validate_on_submit():
        pitch = form.pitch.data
        title = form.title.data
        new_pitch= Pitch( title=title, pitch=pitch, user_id=current_user.id)
        new_pitch.save_pitch() 
        return redirect(url_for('.category', id=category.id))


    title = 'New Pitch'
    return render_template('new_pitch.html', title=title, pitch_form=form, category=category)

@main.route('/write_comment/<int:id>', methods=['GET', 'POST'])
@login_required
def post_comment(id):
    ''' 
    function to post comments 
    '''
    form = CommentForm()
    title = 'post comment'
    pitches = Pitch.query.filter_by(id=id).first()

    if pitches is None:
         abort(404)

    if form.validate_on_submit():
        opinion = form.opinion.data
        new_comment = Comments(opinion=opinion, user_id=current_user.id, pitches_id=pitches.id)
        new_comment.save_comment()
        return redirect(url_for('.view_pitch', id=pitches.id))

    return render_template('post_comment.html', comment_form=form, title=title)

@main.route('/categories/view_pitch/<int:id>', methods=['GET', 'POST'])
@login_required
def view_pitch(id):
 

    print(id)
    pitch = Pitch.get_pitches (id)
   

    if pitch is None:
        abort(404)

    comment = Comments.get_comments(id)
    return render_template('view-pitch.html', pitch=pitch, comment=comment, category_id=id)

app/templates/base.html
{%import 'macros.html' as macro%}
<!doctype html>
<html>
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-secondary">
        <a class="navbar-brand" href="#">JUST MINUTE PITCH</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
	     <span class="navbar-toggler-icon"></span>
	 </button>
     <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="/">Home
                    <span class="sr-only">(current)</span>
                </a>
            </li>

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    categories
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    
                </div>
            </li>
        </ul>
        <ul class="navbar-nav navbar-right">
            {% if current_user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="/">{{current_user.username.capitalize()}}</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{url_for('auth.logout')}}">Sign Out</a>
            </li>
            {%else%}
            <li class="nav-item">
                <a class="nav-link" href="{{url_for('auth.login')}}">Sign In</a>
            </li>
            {%endif%}
        </ul>
    </div>
    </nav>
    {% block content %}
    {% endblock %}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

app/templates/category.html
{% extends 'base.html' %} {% import 'macros.html' as macro%}
{%block styles%}
  {{ super() }}
     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@700&display=swap" rel="stylesheet">

{%endblock%}

<!-- content block -->
{% block content %}
  <div class=" col-md-10 col-md-offset-1 col-sm-12">
   <div class="container" style="text-align:center">
     <div class=" col-md-10 col-md-offset-1 col-sm-12">
       <hr>
  </div>
       <a class="btn btn-primary " href="/categories/new-pitch/add/{{category.id}}"><h4 style="font-size: 20px; text-align:center; font-family: 'Dancing Script', cursive;"> Post a Pitch</h4></a>
       <hr>
  </div>
  
  {% if pitch %}
      <div class="col-sm-12 col-md-8">
          {{ macro.displayPitchList(pitch)}}
      </div>
  {%else%}
        <div class="">
          <h4 style="padding:20%; text-align:center; font-size: 20px; text-align:center; font-family: 'Dancing Script', cursive;">NO PITCHES HERE!</h4>
        </div>
  {% endif %}

{% endblock %}

app/templates/fourOwfour.html
{% extends 'base.html' %}

{% block styles %}
{{ super() }}
<link rel="stylesheet" href="{{url_for('static',filename='css/fourOwfour.css')}}">

{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-4">
            <div class="error-template">
                <h1>Ooops!</h1>
                <h2>Page Not Found</h2>
                <div class="error-details">
                    Sorry,but an error has occured,The requested page was not found!
                </div>
            </div>
            <div class="error-actions">
                <br>
                <a href="/"class="btn btn-secondary btn-lg"><span class="glyphicon glyphicon-home"></span>Navigate Home</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/index.html
{% extends 'base.html'%}
{% import 'macros.html' as macro%}
{% import 'bootstrap/wtf.html' as wtf %}


{% block styles%}
    {{ super() }}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Shrikhand&display=swap" rel="stylesheet">
    
    
{% endblock %}

{% block content %}
<br>
<div class="section1">
    <div class="row"> 
        <div class="container" id="block-text">
        <div class="col">
        <p style="font-size: 20px; font-family: 'Shrikhand', cursive;">In just 60 seconds test your skills and Write a pitch</strong> </p>
        </div>
    </div>
   </div>
</div>

<hr>

<div class="container-fluid">
 
    <h3 font-family: 'Shrikhand', cursive;><a class="btn btn-primary" href="/add/category" style="background-color:blue; float:right;">ADD CATEGORY</a></h3>   
    <h2 style="text-align:center; color:blue; font-family: 'Dancing Script', cursive;">PITCH CATEGORIES </strong></h2>
<hr>
    <strong style="font-size: 20px; text-align:center; font-family: 'Dancing Script', cursive;">{{ macro.displayCategoryList(category) }} </strong>
    
   
</div>


{% endblock  %}

app/templates/interview.html
{% extends 'base.html' %}
{% import 'macros.html' as macro %}

{% block styles %}
{{ super() }}
<link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
{% endblock %}

{% block content %}
<div class="container">
    <h3>Interview Pitches</h3>
    <a href="{{url_for('main.new_pitch')}}">
        <br>
        Add a new Pitch
    </a>
    <hr>
    {{macro.displayPitches(pitches,1)}}<a href="{{url_for('main.new_comment')}}">Comment</a>
    <hr>
</div>
{% endblock%}

app/templates/macros.html
{% macro displayCategoryList(category_list) %}
<div class="container-fluid">
  <div class="row">
	 {% if category_list %}
		{% for category in category_list %}
		<div class="col">
			<div class="card-body">	
				<div class="container">
				    <div class="col-md-6">
			            <div class="thumbnail text-center">
                           <a href="{{url_for('main.category',id=category.id)}}"><p>{{category.name}}</p></a>
                      </div>
		           </div>
			  </div>
	 	   </div>

		</div>
		{% endfor %}
		{% endif %}
	</div>
</div>

{% endmacro %}

{% macro displayPitches(pitch_list) %}
<ul>
    <div class="container-fluid">
			{% for pitches in pitch_list %}
				<div class="row text-center">
						<a><p>{{ comment.description }}</p></a>
						<h3>{{pitches.pitch}}</h3>
				</div>
			{% endfor %}
	
	</div>		
</ul>
{% endmacro %}

{% macro displayPitchList(pitch_list) %}
<div class="container-fluid">
  <div class="row">
	 {% if pitch_list %}
		{% for pitch in pitch_list %}
		<div class="col">
			<div class="card-body">	
				<div class="container">
				    <div class="col-md-6">
			            <div class="thumbnail text-center">
                           <p>{{pitch.name}}</p>
                      </div>
		           </div>
			  </div>
	 	   </div>

		</div>
		{% endfor %}
		{% endif %}
	</div>
</div>

{% endmacro %}

app/templates/navbar.html
<!-- {%import 'macros.html' as macro%}
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <a class="navbar-brand" href="/">PITCH</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="/">Home
                    <span class="sr-only">(current)</span>
                </a>
            </li>

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    categories
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    {{macro.displayCategory(categories)}}
                </div>
            </li>
        </ul>
        <ul class="navbar-nav navbar-right">
            {% if current_user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="/">{{current_user.username.capitalize()}}</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{url_for('auth.logout')}}">Sign Out</a>
            </li>
            {%else%}
            <li class="nav-item">
                <a class="nav-link" href="{{url_for('auth.login')}}">Sign In</a>
            </li>
            {%endif%}
        </ul>
    </div>
</nav> -->

app/templates/new_category.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block styles %}
{{ super() }}

{% endblock %}
{% block content %}
<title>{{ title }}</title>
<div class="container">
    <div class="row">
        <div class="col-md-2 col-lg-2">

        </div>
        <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 create-group">{{ wtf.quick_form(category_form) }}</div>
    </div>
    <div class="col-md-2 col-lg-2">

    </div>
</div>
{% endblock %}

app/templates/new_pitch.html
{% extends 'base.html'%}
{% import 'macros.html' as macro%}
{% import 'bootstrap/wtf.html' as wtf %}
 {%block styles%}
  {{ super() }}
     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@700&display=swap" rel="stylesheet">

{%endblock%}

{% block content %}
<div class="container" style="text-align:center">
     <div class=" col-md-10 col-md-offset-1 col-sm-12">
       <hr>
  </div>
  <div class="well">
    <hr>
    {{wtf.quick_form(pitch_form)}}
 </div>
</div>
{% endblock %}

app/templates/post_comment.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block styles %}
{{ super() }}
{% endblock %}

{% block content %}
<div class="container">
    {{wtf.quick_form(comment_form)}}
</div>
{% endblock %}

app/templates/view-pitch.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}

{%block content%}
{% include 'navbar.html'%}
  {%for pitches in pitch%}
  {{pitches.title}}
  {%endfor%}
{% endblock %}

 